WORKSHOP WEEK-1

4) TO-DO List

    4.1. Warming Up Exercise





In [ ]:
# Import numpy for further use down below

import numpy as np

In [ ]:
# 1. Initialize an empty array with size 2X2.

empty_array = np.empty((2,2))
print(f"2 x 2 empty array: \n {empty_array}")

2 x 2 empty array: 
 [[4.46265178e-315 0.00000000e+000]
 [5.97819431e-322 2.26233621e-076]]


In [ ]:
# 2. Initialize an all one array with size 4X2.

ones_array = np.ones((4,2))
print(f"2 x 2 ones array: \n {ones_array}")

2 x 2 ones array: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
def fill_value_array(shape, dtype, fill_value):

  new_array = np.full((shape), fill_value, dtype)
  return new_array

shape = 2,2
dtype = int
fill_value = 101

print(f"New Array of shape: {shape}, Dtype: {dtype}, Fill_value: {fill_value}; \n{fill_value_array(shape, dtype, fill_value)}")



New Array of shape: (2, 2), Dtype: <class 'int'>, Fill_value: 101; 
[[101 101]
 [101 101]]


In [ ]:
def new_zeros_array(given_array):

  new_array = np.zeros_like(given_array)
  return new_array

given_array = np.array([[2, 3], [5, 4]])

print(f"New Array from given array: \n{given_array}; \n{new_zeros_array(given_array)}")



New Array from given array: 
[[2 3]
 [5 4]]; 
[[0 0]
 [0 0]]


In [ ]:
def new_ones_array(given_array):

  new_array = np.ones_like(given_array)
  return new_array

given_array = np.array([[2, 3], [5, 4]])

print(f"New Array from given array: \n{given_array}; \n{new_ones_array(given_array)}")


New Array from given array: 
[[2 3]
 [5 4]]; 
[[1 1]
 [1 1]]


In [ ]:
new_list = [1,2,3,4]

new_array = np.array(new_list)

print(f"Array: {new_array}, Dimension: {new_array.ndim}, Dtype: {new_array.dtype}")

Array: [1 2 3 4], Dimension: 1, Dtype: int64


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:
# 1. Create an array with values ranging from 10 to 49.

range_array = np.arange(10, 45)
print(f"Array From Range: (10, 45): \n{range_array}")

Array From Range: (10, 45): 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44]


In [ ]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8.

range_array = np.arange(9)
array_3d = range_array.reshape(3, 3)

print(f"3x3 array from range: (0 - 8): \n{array_3d}")

3x3 array from range: (0, 8): 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Create a 3X3 identity matrix.

array_3d_id = np.eye(3)
print(f"3x3 Identity matrix: \n{array_3d_id}")

3x3 Identity matrix: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.

random_array = np.random.rand(30)

array_mean = random_array.mean()

print(f"Random array generated: \n{random_array} \n&\n Mean of the array: {array_mean}")

Random array generated: 
[0.07422382 0.87250363 0.76816735 0.78129994 0.73202809 0.69012704
 0.97502498 0.56158507 0.69963569 0.70618881 0.0227756  0.16353398
 0.58102765 0.91355112 0.1240512  0.22772041 0.08405553 0.28823223
 0.69900268 0.14237924 0.07598086 0.81248512 0.68379191 0.88311682
 0.55096344 0.18478292 0.22089938 0.66242384 0.56700264 0.25153475] 
&
 Mean of the array: 0.5000031909687401


In [ ]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values.

random_array = np.random.rand(10, 10)

array_maximum = random_array.max()
array_minimum = random_array.min()

print(f"Random 10x10 array generated: \n{random_array} \n&\n Min = {array_minimum} & Max = {array_maximum}")


Random 10x10 array generated: 
[[0.66216653 0.04102685 0.81693494 0.65059139 0.84470791 0.90368324
  0.07602771 0.06371983 0.41468498 0.07618207]
 [0.33763443 0.7018021  0.10913851 0.31871634 0.95326326 0.72567729
  0.15320733 0.71888179 0.83161631 0.58036714]
 [0.34355062 0.11356331 0.51227688 0.19587492 0.82739642 0.11953423
  0.07281225 0.1611297  0.71251611 0.50638307]
 [0.75818804 0.25398905 0.27868808 0.22046176 0.91822074 0.8845777
  0.01774898 0.81454872 0.82341713 0.06235172]
 [0.34713684 0.18766201 0.74120246 0.9848296  0.95200483 0.99252671
  0.83708695 0.01733576 0.84110634 0.4107507 ]
 [0.98209103 0.71741984 0.88224614 0.84934033 0.73676261 0.75469953
  0.57976496 0.78391432 0.6246973  0.98611581]
 [0.16061553 0.54541738 0.82116035 0.32542969 0.46868203 0.34683803
  0.08963396 0.03676331 0.04898165 0.15795936]
 [0.05090421 0.90783735 0.83442795 0.95336121 0.88186735 0.81143684
  0.55147803 0.68154737 0.23238869 0.03048998]
 [0.19730552 0.82743845 0.79396463 0.51283372 0.81

In [ ]:
# 6. Create a zero array of size 10 and replace 5th element with 1.

zero_array10 = np.zeros((10))
print(f"Initial array: \n{zero_array10}")

np.put(zero_array10, 4, 1)
print(f"New array: \n{zero_array10}")

Initial array: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
New array: 
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Reverse an array arr = [1,2,0,0,4,0].

arr = [1,2,0,0,4,0]
reverse_arr = np.flip(arr)

# or
# reverse_arr = arr[::-1]

print(f"Given array: \n{arr} \n& \nReverse array: \n{reverse_arr}")


Given array: 
[1, 2, 0, 0, 4, 0] 
& 
Reverse array: 
[0, 4, 0, 0, 2, 1]


In [ ]:
# 8. Create a 2d array with 1 on border and 0 inside.

# np.ones() to create a array with all ones
array_2d = np.ones((4,4))

# using slicing method
array_2d[1:-1, 1:-1] = 0

# creating it manually eg: 3x3 matrix
# array_2d = np.array([[1, 1, 1], [1, 0, 1], [1, 1, 1]])

print(f"2d array of 4x4 with 1s on border and 0s inside: \n{array_2d}")



2d array of 4x4 with 1s on border and 0s inside: 
[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

checker_matrix = np.full((8,8),"■")
checker_matrix[0::2,1::2] = "□"
checker_matrix[1::2,0::2] = "□"

print(f"8x8 Checkerboard pattern matrix: \n{checker_matrix}")

8x8 Checkerboard pattern matrix: 
[['■' '□' '■' '□' '■' '□' '■' '□']
 ['□' '■' '□' '■' '□' '■' '□' '■']
 ['■' '□' '■' '□' '■' '□' '■' '□']
 ['□' '■' '□' '■' '□' '■' '□' '■']
 ['■' '□' '■' '□' '■' '□' '■' '□']
 ['□' '■' '□' '■' '□' '■' '□' '■']
 ['■' '□' '■' '□' '■' '□' '■' '□']
 ['□' '■' '□' '■' '□' '■' '□' '■']]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [ ]:
# Initial given arrays

# First pair or arrays
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(f"X: \n{x} \n&\nY: \n{y}\n")

# Second pair of arrays
v = np.array([9,10])
w = np.array([11,12])
print(f"V: \n{v} \n&\nW: \n{w}")

X: 
[[1 2]
 [3 5]] 
&
Y: 
[[5 6]
 [7 8]]

V: 
[ 9 10] 
&
W: 
[11 12]


In [ ]:
# 1. Add the two array.

# For first pair
x_plus_y = np.add(x, y)
print(f"X + Y: \n {x_plus_y}\n")

# For second pair
v_plus_w = v + w
print(f"V + W: \n {v_plus_w}\n")


X + Y: 
 [[ 6  8]
 [10 13]]

V + W: 
 [20 22]



In [ ]:
# 2. Subtract the two array.

# For first pair
x_minus_y = np.subtract(x, y)
print(f"X - Y: \n {x_minus_y}\n")

# For second pair
v_minus_w = v - w
print(f"V - W: \n {v_minus_w}\n")


X - Y: 
 [[-4 -4]
 [-4 -3]]

V - W: 
 [-2 -2]



In [ ]:
# 3. Multiply the array with any integers of your choice.

# For first pair multiply each array with 5
x_multiply5 = np.multiply(x, 5)
y_multiply5 = np.multiply(y, 5)
print(f"5X: \n {x_multiply5}\n5Y: \n {y_multiply5}\n")

# For second pair multiply each array with 10
v_multiply10 = v * 10
w_multiply10 = w * 10
print(f"10V: \n {v_multiply10}\n10W: \n {w_multiply10}\n")

5X: 
 [[ 5 10]
 [15 25]]
5Y: 
 [[25 30]
 [35 40]]

10V: 
 [ 90 100]
10W: 
 [110 120]



In [ ]:
# 4. Find the square of each element of the array.

# For each array
x_square = np.square(x)
y_square = np.square(y)
v_square = v * v
w_square = w * w

print(f"Square of X: \n{x_square}\nY: \n{y_square}\nV: \n{v_square}\nW: \n{w_square}")


Square of X: 
[[ 1  4]
 [ 9 25]]
Y: 
[[25 36]
 [49 64]]
V: 
[ 81 100]
W: 
[121 144]


In [ ]:
# 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

# For X.Y
x_dot_y = np.dot(x, y)

# For V.W
v_dot_w = np.dot(v, w)

# For X.V
x_dot_v = np.dot(x, v)

print(f"For X.y: \n{x_dot_y}\nV.W: \n{v_dot_w}\nX.V: \n{x_dot_v}")

For X.y: 
[[19 22]
 [50 58]]
V.W: 
219
X.V: 
[29 77]


In [ ]:
# 6. Concatenate x(and)y along row and Concatenate v(and)w along column.

# For first pair
x_con_y = np.concatenate((x, y), axis = 1)

# For second pair
v_con_w = np.vstack((v, w))

print(f"For x and y: \n{x_con_y}\n &\nv and w: \n{v_con_w}")

For x and y: 
[[1 2 5 6]
 [3 5 7 8]]
 &
v and w: 
[[ 9 10]
 [11 12]]


In [ ]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

x_con_v_column = np.concatenate((x, v), axis =0)

x_con_v_row = np.concatenate((x, v), axis = 1)

"""
Ans:- Trying to concatenate x and v resuts in error because x contains 2 dimensional array and v contains 1 dimentional array
But concatenation requires both arrays to be of same dimension. Hence, the error in output.
"""


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem - 4: Matrix Operations:



*  For the following arrays:

    A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
    
    Prove following with Numpy:
    1. Prove A.A^−1 = I.
    2. Prove AB̸ = BA.
    3. Prove (AB)^T = B^T A^T
*   Solve the following system of Linear equation using Inverse Methods.

    2x − 3y + z = −1

    x − y + 2z = −3
    
    3x + y − z = 9
  

*   Now: solve the above equation using np.linalg.inv function.





In [ ]:
# Given arrays:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [ ]:
# 1. Prove A.A^−1 = I.

# L.H.S
A_inverse = np.linalg.inv(A)
A_dot_Ainv = np.dot(A, A_inverse)
print(f"L.H.S: \n{A_dot_Ainv}")

# RHS
I = np.identity(2)
print(f"R.H.S: \n{I}")

# verify
verify = np.allclose(A_dot_Ainv, I)
print(f"Hence, A.A^−1 = I is {verify}")

L.H.S: 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
R.H.S: 
[[1. 0.]
 [0. 1.]]
Hence, A.A^−1 = I is True


In [ ]:
# 2. Prove AB̸= BA.

# L.H.S
A_dot_B = np.dot(A, B)
print(f"L.H.S: \n{A_dot_B}")

# R.H.S
B_dot_A = np.dot(B, A)
print(f"R.H.S: \n{B_dot_A}")

# verify
verify = np.allclose(A_dot_B, B_dot_A)
print(f"Hence, AB̸= BA is {not verify}")

L.H.S: 
[[23 13]
 [51 29]]
R.H.S: 
[[36 44]
 [13 16]]
Hence, AB̸= BA is True


In [ ]:
# 3. Prove (A.B)^T = B^T.A^T

# L.H.S
A_dot_B = np.dot(A, B)
AB_trans = np.transpose(A_dot_B)
print(f"L.H.S: \n{AB_trans}")

# R.H.S
B_trans = np.transpose(B)
A_trans = np.transpose(A)
Btrans_dot_Atrans = np.dot(B_trans, A_trans)
print(f"R.H.S: \n{Btrans_dot_Atrans}")

# verify
verify = np.allclose(AB_trans, Btrans_dot_Atrans)
print(f"Hence, (A.B)^T = B^T.A^T is { verify}")

L.H.S: 
[[23 51]
 [13 29]]
R.H.S: 
[[23 51]
 [13 29]]
Hence, (A.B)^T = B^T.A^T is True


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1

# x − y + 2z = −3

# 3x + y − z = 9

# Initialize the given linear equations into matrix equation form AX = B

A = np.array([[2, 3, 1], [1, -1, 2], [3, 1, -1]])
X = np.array(["x", "y", "z"])
B = np.array([-1, -3, 9])




In [ ]:
# Now: solve the above equation using np.linalg.inv function.

# Equation: AX = B; X = A^-1.B

A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)

print(f"The value of X: {X[0]}; Y: {X[1]}; Z: {X[2]}")

The value of X: 2.2608695652173916; Y: -0.8260869565217391; Z: -3.043478260869565


Experiment: How Fast is Numpy?

In [ ]:
# 1. Element-wise Addition:

import random

from timeit import timeit

def add_python(r1, r2):
 return [r1 + r2 for r1, r2 in zip(r1, r2)]

def add_numpy(r1, r2):
 return np.add(r1, r2)

list1 = random.sample(range(1000000), 1000000)
list2 = random.sample(range(1000000), 1000000)

array1 = np.array(list1)
array2 = np.array(list2)

# Using Python list:
time_python = timeit("add_python(list1, list2)", globals = globals(), number = 1000)
print(f"Time taken by python list to execute the operation: {time_python}")

# Using Numpy array:
time_numpy = timeit("add_numpy(array2, array2)", globals = globals(), number = 1000)
print(f"Time taken by numpy array to execute the operation: {time_numpy}")

Time taken by python list to execute the operation: 210.06007324500024
Time taken by numpy array to execute the operation: 0.8616231129999505


In [ ]:
# 2. Element-wise Multiplication:

import random

from timeit import timeit

def multiply_python(r1, r2):
 return [r1 * r2 for r1, r2 in zip(r1, r2)]

def multiply_numpy(r1, r2):
 return np.multiply(r1, r2)

list1 = random.sample(range(1000000), 1000000)
list2 = random.sample(range(1000000), 1000000)

array1 = np.array(list1)
array2 = np.array(list2)

# Using Python list:
time_python = timeit("multiply_python(list1, list2)", globals = globals(), number = 1000)
print(f"Time taken by python list to execute the operation: {time_python}")

# Using Numpy array:
time_numpy = timeit("multiply_numpy(array1, array2)", globals = globals(), number = 1000)
print(f"Time taken by numpy array to execute the operation: {time_numpy}")

Time taken by python list to execute the operation: 245.63757913000154
Time taken by numpy array to execute the operation: 1.648629143001017


In [ ]:
# 3. Element-wise dot product:

import random

from timeit import timeit

def dot_python(r1, r2):
 return sum(r1 * r2 for r1, r2 in zip(r1, r2))

def dot_numpy(r1, r2):
 return np.dot(r1, r2)

list1 = random.sample(range(1000000), 1000000)
list2 = random.sample(range(1000000), 1000000)

array1 = np.array(list1)
array2 = np.array(list2)

# Using Python list:
time_python = timeit("dot_python(list1, list2)", globals = globals(), number = 1000)
print(f"Time taken by python list to execute the operation: {time_python}")

# Using Numpy array:
time_numpy = timeit("dot_numpy(array1, array2)", globals = globals(), number = 1000)
print(f"Time taken by numpy array to execute the operation: {time_numpy}")

Time taken by python list to execute the operation: 275.9540988739991
Time taken by numpy array to execute the operation: 2.250331969000399


In [ ]:
# 4. Element-wise Matrix Multiplication:

import random

from timeit import timeit

def matrix_multiply_python(r1, r2):
 result = [[0] * len(r2[0]) for row in range(len(r1))]
 for i in range(len(r1)):
  for j in range(len(r2[0])):
    for k in range(len(r2)):
      result[i][j] += r1[i][k] * r2[k][j]
 return result

def matrix_multiply_numpy(r1, r2):
 return np.dot(r1, r2)

matrix_list1 = [[random.randint(1, 10) for col in range(1000)] for row in range(1000)]
matrix_list2 = [[random.randint(1, 10) for col in range(1000)] for row in range(1000)]

matrix_array1 = np.array(matrix_list1)
matrix_array2 = np.array(matrix_list2)

# Using Python list:
time_python = timeit("matrix_multiply_python(matrix_list1, matrix_list2)", globals = globals(), number = 1000)
print(f"Time taken by python list to execute the operation: {time_python}")

# Using Numpy array:
time_numpy = timeit("matrix_multiply_numpy(matrix_array1, matrix_array2)", globals = globals(), number = 1000)
print(f"Time taken by numpy array to execute the operation: {time_numpy}")

KeyboardInterrupt: 